# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new .gitlab-ci.yml file.
# You should not add this template to an existing .gitlab-ci.yml file by using the include: keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml
stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  image: maven:3.8.4-openjdk-17
  script:
    - echo "Код компилириуется"
    - mvn clean
    - mvn package
    - echo "Код скомпилировался."

unit-test-job:
  stage: test
  image: maven:3.8.4-openjdk-17
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - mvn test
    - echo "Code coverage is 90%"

deploy-job:
  stage: deploy
  image: docker:20.10.16
  environment: production
  script:
    - echo "building docker compose.."
    - docker build -t spring-web-image .
    - docker run -d -p 8008:8008 spring-web-image
    - echo "Application successfully deployed."