spring:
  mail:
    host: email-smtp.eu-north-1.amazonaws.com
    port: 465
    username: AKIATCKARC3E2F6KUPE7
    password: BByvrO7cwb7Ia/BsSYCGrmuNfYdxgg1Yi4L3PNhfU1wW
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*"
            enable: true
  web:
    resources:
      static-locations: classpath:/static/
  thymeleaf:
    cache: false
    encoding: UTF-8
  datasource:
    url: jdbc:postgresql://spring-database.c1q8kaii42b6.eu-north-1.rds.amazonaws.com/postgres
    username: postgres
    password: r20o07NDFsh123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: update
jwt:
  secret: a23rser3fwa3r4fawerfagy53uyt73
  lifetime: 3d
server:
  port: 8008
  error:
    whitelabel:
      enabled: false
    path: /error
