spring:
  thymeleaf:
    cache: true
    encoding: UTF-8
  datasource:
    url: jdbc:postgresql://localhost:5432/blogdatabase
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
server:
  port: 8008
